name: Update map data from SharePoint

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * *"   # ~2:00 AM Central during CDT (UTC-5)
    - cron: "0 8 * * *"   # ~2:00 AM Central during CST (UTC-6)

permissions:
  contents: write

jobs:
  update-json:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull SharePoint list and build JSON
        shell: pwsh
        env:
          GRAPH_TENANT_ID:  ${{ secrets.GRAPH_TENANT_ID }}
          GRAPH_CLIENT_ID:  ${{ secrets.GRAPH_CLIENT_ID }}
          GRAPH_CLIENT_SECRET: ${{ secrets.GRAPH_CLIENT_SECRET }}
          SP_SITE_URL:      ${{ secrets.SP_SITE_URL }}      # e.g. https://gatewaymgt.sharepoint.com/sites/Intranet
          SP_LIST_NAME:     ${{ secrets.SP_LIST_NAME }}     # e.g. Properties_by_RVP
        run: |
          # ---- Derive hostname/path from SP_SITE_URL so we don't need extra secrets ----
          $u = [uri]$env:SP_SITE_URL
          $siteHostname = $u.Host
          $sitePath     = $u.AbsolutePath   # e.g. /sites/Intranet

          # ---- Get Graph token (client credentials) ----
          $body = @{
            client_id     = $env:GRAPH_CLIENT_ID
            scope         = "https://graph.microsoft.com/.default"
            client_secret = $env:GRAPH_CLIENT_SECRET
            grant_type    = "client_credentials"
          }
          $tok = Invoke-RestMethod -Method Post -Uri "https://login.microsoftonline.com/$($env:GRAPH_TENANT_ID)/oauth2/v2.0/token" -Body $body
          $H = @{ Authorization = "Bearer $($tok.access_token)" }

          # ---- Resolve site + list ----
          $siteUri = "https://graph.microsoft.com/v1.0/sites/$siteHostname:$sitePath"
          $site    = Invoke-RestMethod -Headers $H -Uri $siteUri
          $siteId  = $site.id

          $listName = $env:SP_LIST_NAME
          $lists = Invoke-RestMethod -Headers $H -Uri "https://graph.microsoft.com/v1.0/sites/$siteId/lists?`$filter=displayName eq '$listName'&`$select=id,displayName"
          if(-not $lists.value){ throw "List '$listName' not found at $($env:SP_SITE_URL)" }
          $listId = $lists.value[0].id

          # ---- Pull all items (expand fields) ----
          $items = @()
          $url = "https://graph.microsoft.com/v1.0/sites/$siteId/lists/$listId/items?`$expand=fields&`$top=999"
          while($url){
            $r = Invoke-RestMethod -Headers $H -Uri $url
            $items += $r.value
            $url = $r.'@odata.nextLink'
          }

          # ---- First run helper: dump detected internal field names ----
          if($items.Count -gt 0){
            ($items[0].fields | Get-Member -MemberType NoteProperty | Select -ExpandProperty Name |
              Sort-Object) | Out-File -Encoding utf8 -FilePath "$PWD/detected_sharepoint_fields.txt"
          }

          # ---- Map SharePoint fields -> schema your app.js expects (adjust as needed) ----
          function Map-Row($f){
            [pscustomobject]@{
              name           = $f.Title            # Property
              type           = $f.TYPE             # Type
              units          = $f.field_2          # Units
              manager        = $f.field_3          # Manager
              assistant_mgr  = $f.field_4          # Assistant MGR
              compliance     = $f.field_5          # Compliance Specialist
              address        = $f.field_6          # Street
              city           = $f.field_7
              state          = $f.field_8
              zip            = $f.field_9
              office_phone   = $f.field_10         # Office
              fax            = $f.field_11
              manager_email  = $f.field_12
              rpm            = $f.field_13         # RPM
              rvp            = $f.field_14         # RVP
              lat            = [double]$f.Latitude
              lng            = [double]$f.Longitude
              owner          = $f.Owner

            }
          }

          $out = foreach($it in $items){ Map-Row $it.fields }

          # ---- Backup previous JSON if exists ----
          $jsonFile = "final_properties_with_coords_and_rvp.json"
          if (Test-Path $jsonFile) {
            $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
            Copy-Item $jsonFile "backup_final_properties_$stamp.json"
          }

          # ---- Write JSON expected by the frontend ----
          $out | ConvertTo-Json -Depth 4 | Set-Content -Encoding utf8 -Path $jsonFile
          Write-Host "Wrote $jsonFile with $($out.Count) rows."

      - name: Commit JSON (and first-time field list)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update: final_properties_with_coords_and_rvp.json from SharePoint"
          file_pattern: |
            final_properties_with_coords_and_rvp.json
            backup_final_properties_*.json
            detected_sharepoint_fields.txt
          commit_user_name: ${{ secrets.COMMIT_USER_NAME || 'Gateway Map Bot' }}
          commit_user_email: ${{ secrets.COMMIT_USER_EMAIL || 'bot@example.com' }}
